### ISSUE TITLE
[Question] Documentation

### ISSUE THREAD

**Issue by RobertSuto** [sampullman/android-PuzzleDroid#1]
Hello, I've recently discovered this repo, and I was wondering if you have some sort of documentation for the project.
Thanks in advance!

**Comment by sampullman** [comment]
Hi Robert! This project is pretty ancient, I wrote it ~10 years ago and threw it up on Github 5 years ago because it seemed like a waste not to.

To be honest, I barely remember anything about it. Apparently the [graphics library](https://github.com/sampullman/android-mgraphicslib/tree/master/mgraphicslib/src/main/java/com/threeDBJ/MGraphicsLib) and cube implementation is a mostly dependency free OpenGL wrapper, which is kind of neat.

I have no idea how much effort it would even take to get this to compile again, and the code quality is probably what you'd expect from a college kid, so I'm not sure it's very useful for anything.
